# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
